// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Renderer is an autogenerated mock type for the Renderer type
type Renderer struct {
	mock.Mock
}

// Clear provides a mock function with no fields
func (_m *Renderer) Clear() {
	_m.Called()
}

// DrawBall provides a mock function with given fields: x, y, radius
func (_m *Renderer) DrawBall(x float64, y float64, radius float64) {
	_m.Called(x, y, radius)
}

// DrawDebugText provides a mock function with given fields: text, x, y
func (_m *Renderer) DrawDebugText(text string, x float64, y float64) {
	_m.Called(text, x, y)
}

// DrawPaddle provides a mock function with given fields: x, y, w, h
func (_m *Renderer) DrawPaddle(x float64, y float64, w float64, h float64) {
	_m.Called(x, y, w, h)
}

// DrawText provides a mock function with given fields: text, x, y
func (_m *Renderer) DrawText(text string, x float64, y float64) {
	_m.Called(text, x, y)
}

// MeasureText provides a mock function with given fields: text
func (_m *Renderer) MeasureText(text string) float64 {
	ret := _m.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for MeasureText")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(text)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// NewRenderer creates a new instance of Renderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Renderer {
	mock := &Renderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
